

services:
  marker_app:
    image: xiaoyao9184/marker:1.7.2
    container_name: marker_pdf_app
    environment:
      - TORCH_DEVICE=cpu
      - HF_HUB_OFFLINE=true
      - DETECTOR_MODEL_CHECKPOINT=/root/.cache/datalab/models/text_detection/2025_05_07
      - RECOGNITION_MODEL_CHECKPOINT=/root/.cache/datalab/models/text_recognition/2025_05_16
      - LAYOUT_MODEL_CHECKPOINT=/root/.cache/datalab/models/layout/2025_02_18
      - OCR_ERROR_MODEL_CHECKPOINT=/root/.cache/datalab/models/ocr_error_detection/2025_02_18
      - TABLE_REC_MODEL_CHECKPOINT=/root/.cache/datalab/models/table_recognition/2025_02_18
      # - FONT_DIR=/fonts # not work
    ports:
      - "8501:8501"
    volumes:
      - ./../../cache:/root/.cache
      # - ./../../static/fonts:/fonts # not work
      # - ./../../static/fonts:/opt/conda/lib/python3.11/site-packages/static/fonts # image already included
